version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: meduzzen_backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: meduzzen_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: